CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE,
  passwordHash VARCHAR(255),
  role VARCHAR(50),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE UserPasswordHistory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(userId)
);

CREATE TABLE PasswordChangeAttempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  ip VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(userId),
  INDEX(createdAt),
  INDEX(ip)
);

CREATE TABLE Address (
  id INT AUTO_INCREMENT PRIMARY KEY,
  line1 VARCHAR(255),
  line2 VARCHAR(255),
  line3 VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationAbout (
  id INT PRIMARY KEY,
  text MEDIUMTEXT,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationAboutRevisions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text MEDIUMTEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE InformationNews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  date DATETIME,
  text TEXT NOT NULL,
  content MEDIUMTEXT,
  summary TEXT,
  draft TINYINT DEFAULT 0,
  category VARCHAR(64),
  coverUrl VARCHAR(255),
  previewUrl VARCHAR(255),
  position INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationNewsRevisions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  newsId INT,
  title VARCHAR(255),
  date DATETIME,
  text TEXT,
  content MEDIUMTEXT,
  summary TEXT,
  draft TINYINT,
  category VARCHAR(64),
  coverUrl VARCHAR(255),
  previewUrl VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE InformationNewsTrash (
  newsId INT PRIMARY KEY,
  deletedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE InformationGroup (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT,
  title VARCHAR(255),
  position INT DEFAULT 0,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationSolo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT,
  title VARCHAR(255),
  position INT DEFAULT 0,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationAwards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT,
  title VARCHAR(255),
  position INT DEFAULT 0,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationFairs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT,
  title VARCHAR(255),
  position INT DEFAULT 0,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationWebsites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url TEXT,
  label VARCHAR(255),
  position INT DEFAULT 0,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE InformationContacts (
  id INT PRIMARY KEY,
  email VARCHAR(255),
  phone VARCHAR(255),
  address TEXT,
  addressLine1 VARCHAR(255),
  addressLine2 VARCHAR(255),
  addressLine3 VARCHAR(255),
  instagram VARCHAR(255),
  facebook VARCHAR(255),
  website VARCHAR(255),
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WorkSection (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(255) UNIQUE,
  name VARCHAR(255),
  position INT DEFAULT 0,
  visible BOOLEAN DEFAULT TRUE,
  seoTitle VARCHAR(255),
  seoDescription TEXT,
  seoKeywords TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WorkItem (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sectionId INT,
  slug VARCHAR(255) UNIQUE,
  title VARCHAR(255),
  location VARCHAR(255),
  description TEXT,
  year INT,
  type VARCHAR(255),
  collaborators VARCHAR(255),
  position INT DEFAULT 0,
  published BOOLEAN DEFAULT TRUE,
  seoTitle VARCHAR(255),
  seoDescription TEXT,
  seoKeywords TEXT,
  canonicalUrl VARCHAR(255),
  ogImageUrl VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WorkMedia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  itemId INT,
  type ENUM('IMAGE','VIDEO'),
  url TEXT,
  thumbnail TEXT,
  caption TEXT,
  alt TEXT,
  position INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
